[pid: 1726071|app: 0|req: 1/1] 58.250.174.74 () {44 vars in 867 bytes} [Sun May  1 12:34:44 2022] GET / => generated 566 bytes in 1260 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[['test', 335, 1, 2], ['fuck', 335, 1, 1], ['kernel', 335, 0, 1], ['power', 335, 0, 1], ['Froala', 335, 0, 1], ['Editor', 335, 0, 1]]
[['test', 336, 1, 2], ['fuck', 336, 1, 1], ['kernel', 336, 0, 1], ['power', 336, 0, 1], ['Froala', 336, 0, 1], ['Editor', 336, 0, 1]]['test', 335, 1, 2]

['test', 336, 1, 2]
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726074|app: 0|req: 2/2] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:34:59 2022] POST /SetQuestion => generated 71813 bytes in 3090 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726074|app: 0|req: 2/3] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:00 2022] POST /SetQuestion => generated 71813 bytes in 2047 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 1)
[['test', 337, 1, 2], ['fuck', 337, 1, 1], ['kernel', 337, 0, 1], ['power', 337, 0, 1], ['Froala', 337, 0, 1], ['Editor', 337, 0, 1]]
['test', 337, 1, 2]
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726074|app: 0|req: 3/4] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:02 2022] POST /SetQuestion => generated 71813 bytes in 1827 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
[['test', 339, 1, 2], ['fuck', 339, 1, 1], ['kernel', 339, 0, 1], ['power', 339, 0, 1], ['Froala', 339, 0, 1], ['Editor', 339, 0, 1]]
[['test', 338, 1, 2], ['fuck', 338, 1, 1], ['kernel', 338, 0, 1], ['power', 338, 0, 1], ['Froala', 338, 0, 1], ['Editor', 338, 0, 1]]
['test', 339, 1, 2]
['test', 338, 1, 2]
[['test', 340, 1, 2], ['fuck', 340, 1, 1], ['kernel', 340, 0, 1], ['power', 340, 0, 1], ['Froala', 340, 0, 1], ['Editor', 340, 0, 1]]
[['test', 341, 1, 2], ['fuck', 341, 1, 1], ['kernel', 341, 0, 1], ['power', 341, 0, 1], ['Froala', 341, 0, 1], ['Editor', 341, 0, 1]]
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726075|app: 0|req: 2/5] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:01 2022] POST /SetQuestion => generated 71813 bytes in 5709 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
[pid: 1726075|app: 0|req: 2/6] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:01 2022] POST /SetQuestion => generated 71813 bytes in 5485 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 1)
['test', 340, 1, 2]
['test', 341, 1, 2]
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 414, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726073|app: 0|req: 2/7] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:02 2022] POST /SetQuestion => generated 71813 bytes in 5308 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 1)
[pid: 1726073|app: 0|req: 2/8] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:02 2022] POST /SetQuestion => generated 71813 bytes in 5474 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:35:31 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:35:36 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x56047d003ee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x56047d003ee0 pid: 1726439 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1726439)
spawned uWSGI worker 1 (pid: 1726443, cores: 2)
spawned uWSGI worker 2 (pid: 1726445, cores: 2)
spawned uWSGI worker 3 (pid: 1726446, cores: 2)
spawned uWSGI worker 4 (pid: 1726448, cores: 2)
[pid: 1726448|app: 0|req: 1/1] 58.250.174.74 () {44 vars in 867 bytes} [Sun May  1 12:35:40 2022] GET / => generated 566 bytes in 1290 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
here is my test, i will test my kernel here. fuck.Powered by Froala Editor
[['test', 342, 1, 2], ['fuck', 342, 1, 1], ['kernel', 342, 0, 1], ['power', 342, 0, 1], ['Froala', 342, 0, 1], ['Editor', 342, 0, 1]]
['test', 342, 1, 2]
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 415, in setQuestion
    res = cursor.executemany(sql, list(item))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 173, in executemany
    return self._do_execute_many(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 196, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not enough arguments for format string
[pid: 1726446|app: 0|req: 1/2] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:35:52 2022] POST /SetQuestion => generated 71815 bytes in 2132 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
[pid: 1726446|app: 0|req: 2/3] 121.46.142.244 () {40 vars in 661 bytes} [Sun May  1 12:36:13 2022] GET /api/MyGroups/ => generated 30 bytes in 1 msecs (HTTP/1.1 200) 7 headers in 220 bytes (1 switches on core 1)
[pid: 1726446|app: 0|req: 3/4] 121.46.142.244 () {40 vars in 547 bytes} [Sun May  1 12:41:50 2022] HEAD /api/AddViews => generated 9 bytes in 1 msecs (HTTP/1.1 200) 7 headers in 211 bytes (1 switches on core 1)
Sun May  1 12:42:47 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:42:47 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:42:47 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:42:47 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:42:49 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x5653eb205ee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5653eb205ee0 pid: 1728287 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1728287)
spawned uWSGI worker 1 (pid: 1728290, cores: 2)
spawned uWSGI worker 2 (pid: 1728292, cores: 2)
spawned uWSGI worker 3 (pid: 1728293, cores: 2)
spawned uWSGI worker 4 (pid: 1728295, cores: 2)
[pid: 1728295|app: 0|req: 1/1] 58.250.174.74 () {44 vars in 867 bytes} [Sun May  1 12:42:55 2022] GET / => generated 566 bytes in 1260 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
.Powered by Froala Editor
here is my test, my test is fuck. is an a hello.Powered by Froala Editor
[['test', 343, 1, 2], ['fuck', 343, 1, 1], ['hello', 343, 0, 1], ['power', 343, 0, 1], ['Froala', 343, 0, 1], ['Editor', 343, 0, 1]]
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 439, in setQuestion
    data['ok'] = 1
TypeError: list indices must be integers or slices, not str
[pid: 1728295|app: 0|req: 2/2] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:43:24 2022] POST /SetQuestion => generated 61836 bytes in 932 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:47:34 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:47:37 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55bcf63acee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55bcf63acee0 pid: 1729545 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1729545)
spawned uWSGI worker 1 (pid: 1729553, cores: 2)
spawned uWSGI worker 2 (pid: 1729555, cores: 2)
spawned uWSGI worker 3 (pid: 1729556, cores: 2)
spawned uWSGI worker 4 (pid: 1729558, cores: 2)
[pid: 1729558|app: 0|req: 1/1] 58.250.174.74 () {44 vars in 867 bytes} [Sun May  1 12:47:44 2022] GET / => generated 566 bytes in 1270 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
Powered by Froala Editor
here is my test, my test is fuck. is an a hello.P
Powered by Froala Editor
here is my test, my test is fuck. is an a hello.P
[['test', 344, 1, 2], ['fuck', 344, 1, 1], ['hello', 344, 0, 1], ['p', 344, 0, 1]]
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 439, in setQuestion
    data['ok'] = 1
TypeError: list indices must be integers or slices, not str
[pid: 1729558|app: 0|req: 2/2] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:47:59 2022] POST /SetQuestion => generated 61731 bytes in 1357 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 1)
[['test', 345, 1, 2], ['fuck', 345, 1, 1], ['hello', 345, 0, 1], ['p', 345, 0, 1]]
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
Internal Server Error: /SetQuestion
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 439, in setQuestion
    data['ok'] = 1
TypeError: list indices must be integers or slices, not str
[pid: 1729556|app: 0|req: 1/3] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:47:58 2022] POST /SetQuestion => generated 61731 bytes in 2600 msecs (HTTP/1.1 500) 9 headers in 340 bytes (1 switches on core 0)
Sun May  1 12:50:33 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:50:33 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
!!! uWSGI process 1729558 got Segmentation Fault !!!
malloc(): unsorted double linked list corrupted
Sun May  1 12:50:33 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:50:33 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:50:33 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun May  1 12:50:33 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:50:33 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.20 (64bit) on [Sun May  1 20:50:36 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x5623f236fee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5623f236fee0 pid: 1730146 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1730146)
spawned uWSGI worker 1 (pid: 1730149, cores: 2)
spawned uWSGI worker 2 (pid: 1730151, cores: 2)
spawned uWSGI worker 3 (pid: 1730152, cores: 2)
spawned uWSGI worker 4 (pid: 1730153, cores: 2)
[pid: 1730151|app: 0|req: 1/1] 58.250.174.74 () {44 vars in 867 bytes} [Sun May  1 12:50:40 2022] GET / => generated 566 bytes in 1276 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
Powered by Froala Editor
here is my test, my test is fuck. is an a hello.
Powered by Froala Editor
here is my test, my test is fuck. is an a hello.
[['test', 346, 1, 2], ['fuck', 346, 1, 1], ['hello', 346, 0, 1]]
[['test', 347, 1, 2], ['fuck', 347, 1, 1], ['hello', 347, 0, 1]]
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
ordinary insert done
[pid: 1730152|app: 0|req: 2/2] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:50:50 2022] POST /SetQuestion => generated 9 bytes in 2835 msecs (HTTP/1.1 200) 9 headers in 316 bytes (1 switches on core 0)
[pid: 1730152|app: 0|req: 2/3] 58.250.174.74 () {46 vars in 843 bytes} [Sun May  1 12:50:52 2022] POST /SetQuestion => generated 9 bytes in 1453 msecs (HTTP/1.1 200) 9 headers in 316 bytes (1 switches on core 1)
[pid: 1730151|app: 0|req: 3/4] 58.250.174.74 () {46 vars in 849 bytes} [Sun May  1 12:50:53 2022] POST /api/getProfile/ => generated 58 bytes in 69 msecs (HTTP/1.1 200) 9 headers in 317 bytes (1 switches on core 1)
[pid: 1730151|app: 0|req: 4/5] 58.250.174.74 () {46 vars in 837 bytes} [Sun May  1 12:50:53 2022] POST /mainpage/ => generated 5592 bytes in 360 msecs (HTTP/1.1 200) 9 headers in 319 bytes (1 switches on core 0)
[pid: 1730151|app: 0|req: 4/6] 58.250.174.74 () {46 vars in 841 bytes} [Sun May  1 12:50:53 2022] POST /unAnswered/ => generated 12646 bytes in 540 msecs (HTTP/1.1 200) 9 headers in 320 bytes (1 switches on core 1)
[pid: 1730153|app: 0|req: 2/7] 58.250.174.74 () {46 vars in 837 bytes} [Sun May  1 12:50:53 2022] POST /myFollow/ => generated 1772 bytes in 2241 msecs (HTTP/1.1 200) 9 headers in 319 bytes (1 switches on core 0)
[pid: 1730153|app: 0|req: 2/8] 58.250.174.74 () {46 vars in 841 bytes} [Sun May  1 12:50:53 2022] POST /api/Groups/ => generated 4475 bytes in 2303 msecs (HTTP/1.1 200) 9 headers in 319 bytes (1 switches on core 1)
[pid: 1730149|app: 0|req: 2/9] 58.250.174.74 () {46 vars in 845 bytes} [Sun May  1 12:50:53 2022] POST /api/MyGroups/ => generated 1205 bytes in 2327 msecs (HTTP/1.1 200) 9 headers in 319 bytes (1 switches on core 0)
[pid: 1730149|app: 0|req: 2/10] 58.250.174.74 () {46 vars in 841 bytes} [Sun May  1 12:50:53 2022] POST /api/MyBlogs => generated 15335 bytes in 2835 msecs (HTTP/1.1 200) 9 headers in 320 bytes (1 switches on core 1)
