*** Starting uWSGI 2.0.20 (64bit) on [Fri Apr  8 14:18:47 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x557d58949d40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x557d58949d40 pid: 923874 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 923874)
spawned uWSGI worker 1 (pid: 923876, cores: 2)
spawned uWSGI worker 2 (pid: 923878, cores: 2)
spawned uWSGI worker 3 (pid: 923879, cores: 2)
spawned uWSGI worker 4 (pid: 923881, cores: 2)
Not Found: /
[pid: 923878|app: 0|req: 1/1] 14.145.137.58 () {46 vars in 984 bytes} [Fri Apr  8 06:18:56 2022] GET / => generated 4507 bytes in 167 msecs (HTTP/1.1 404) 7 headers in 214 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 923879|app: 0|req: 1/2] 14.145.137.58 () {46 vars in 937 bytes} [Fri Apr  8 06:18:56 2022] GET /favicon.ico => generated 4558 bytes in 152 msecs (HTTP/1.1 404) 7 headers in 214 bytes (1 switches on core 0)
[pid: 923876|app: 0|req: 1/3] 14.145.137.58 () {46 vars in 996 bytes} [Fri Apr  8 06:19:01 2022] GET /index/ => generated 566 bytes in 153 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
qpr
Q@@pr294118
[pid: 923878|app: 0|req: 2/4] 14.145.137.58 () {52 vars in 1052 bytes} [Fri Apr  8 06:19:10 2022] POST /login/ => generated 14 bytes in 142 msecs (HTTP/1.1 200) 10 headers in 464 bytes (1 switches on core 1)
[pid: 923879|app: 0|req: 3/5] 14.145.137.58 () {52 vars in 1070 bytes} [Fri Apr  8 06:19:10 2022] POST /api/getProfile/ => generated 58 bytes in 66 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 1)
[pid: 923876|app: 0|req: 2/6] 14.145.137.58 () {52 vars in 1062 bytes} [Fri Apr  8 06:19:10 2022] POST /api/Groups/ => generated 725 bytes in 115 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 2/7] 14.145.137.58 () {52 vars in 1066 bytes} [Fri Apr  8 06:19:10 2022] POST /api/MyGroups/ => generated 725 bytes in 310 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923879|app: 0|req: 3/8] 14.145.137.58 () {52 vars in 1058 bytes} [Fri Apr  8 06:19:10 2022] POST /myFollow/ => generated 2052 bytes in 337 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 0)
[pid: 923881|app: 0|req: 2/9] 14.145.137.58 () {52 vars in 1058 bytes} [Fri Apr  8 06:19:10 2022] POST /mainpage/ => generated 2503 bytes in 469 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 0)
[pid: 923881|app: 0|req: 4/10] 60.181.111.149 () {50 vars in 910 bytes} [Fri Apr  8 06:31:41 2022] POST /api/getProfile/ => generated 58 bytes in 52 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923879|app: 0|req: 4/11] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:31:41 2022] POST /myFollow/ => generated 2 bytes in 57 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 1)
[pid: 923876|app: 0|req: 4/12] 60.181.111.149 () {50 vars in 906 bytes} [Fri Apr  8 06:31:41 2022] POST /api/MyGroups/ => generated 2 bytes in 83 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923876|app: 0|req: 4/13] 60.181.111.149 () {50 vars in 902 bytes} [Fri Apr  8 06:31:41 2022] POST /api/Groups/ => generated 725 bytes in 89 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 4/14] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:31:41 2022] POST /mainpage/ => generated 2503 bytes in 162 msecs (HTTP/1.1 200) 9 headers in 306 bytes (1 switches on core 0)
[pid: 923881|app: 0|req: 6/15] 60.181.111.149 () {50 vars in 910 bytes} [Fri Apr  8 06:39:51 2022] POST /api/getProfile/ => generated 58 bytes in 53 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 6/16] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:39:51 2022] POST /myFollow/ => generated 2 bytes in 56 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923878|app: 0|req: 3/17] 60.181.111.149 () {50 vars in 906 bytes} [Fri Apr  8 06:39:51 2022] POST /api/MyGroups/ => generated 2 bytes in 85 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923876|app: 0|req: 6/18] 60.181.111.149 () {50 vars in 902 bytes} [Fri Apr  8 06:39:51 2022] POST /api/Groups/ => generated 725 bytes in 93 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 1)
[pid: 923876|app: 0|req: 6/19] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:39:51 2022] POST /mainpage/ => generated 2503 bytes in 239 msecs (HTTP/1.1 200) 9 headers in 306 bytes (1 switches on core 0)
[pid: 923878|app: 0|req: 4/20] 60.181.111.149 () {50 vars in 910 bytes} [Fri Apr  8 06:40:55 2022] POST /api/getProfile/ => generated 58 bytes in 53 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 8/21] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:40:55 2022] POST /myFollow/ => generated 2 bytes in 62 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923879|app: 0|req: 6/22] 60.181.111.149 () {50 vars in 906 bytes} [Fri Apr  8 06:40:55 2022] POST /api/MyGroups/ => generated 2 bytes in 80 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923879|app: 0|req: 6/23] 60.181.111.149 () {50 vars in 902 bytes} [Fri Apr  8 06:40:55 2022] POST /api/Groups/ => generated 725 bytes in 95 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 8/24] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:40:55 2022] POST /mainpage/ => generated 2503 bytes in 178 msecs (HTTP/1.1 200) 9 headers in 306 bytes (1 switches on core 1)
[pid: 923876|app: 0|req: 8/25] 60.181.111.149 () {50 vars in 930 bytes} [Fri Apr  8 06:44:25 2022] POST /api/getProfile/ => generated 58 bytes in 53 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 923881|app: 0|req: 10/26] 60.181.111.149 () {50 vars in 918 bytes} [Fri Apr  8 06:44:25 2022] POST /myFollow/ => generated 2 bytes in 54 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 923881|app: 0|req: 10/27] 60.181.111.149 () {50 vars in 922 bytes} [Fri Apr  8 06:44:25 2022] POST /api/Groups/ => generated 725 bytes in 85 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 1)
[pid: 923878|app: 0|req: 5/28] 60.181.111.149 () {50 vars in 926 bytes} [Fri Apr  8 06:44:25 2022] POST /api/MyGroups/ => generated 2 bytes in 87 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 1)
[pid: 923876|app: 0|req: 8/29] 60.181.111.149 () {50 vars in 918 bytes} [Fri Apr  8 06:44:25 2022] POST /mainpage/ => generated 2503 bytes in 176 msecs (HTTP/1.1 200) 9 headers in 306 bytes (1 switches on core 0)
Internal Server Error: /api/getProfile/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 692, in getProfile
    photo_url = target_user[0]['photo']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 923881|app: 0|req: 12/30] 60.181.111.149 () {50 vars in 930 bytes} [Fri Apr  8 06:44:45 2022] POST /api/getProfile/ => generated 59075 bytes in 152 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
Internal Server Error: /api/MyGroups/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 841, in MyGroups
    response = groups(request, own = 1)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 797, in groups
    user_id = User.objects.filter(username=username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 923881|app: 0|req: 12/31] 60.181.111.149 () {50 vars in 926 bytes} [Fri Apr  8 06:44:45 2022] POST /api/MyGroups/ => generated 62802 bytes in 158 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 1)
Internal Server Error: /mainpage/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 363, in main_page
    userid = User.objects.filter(username = username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 923876|app: 0|req: 9/32] 60.181.111.149 () {50 vars in 918 bytes} [Fri Apr  8 06:44:45 2022] POST /mainpage/ => generated 58969 bytes in 170 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 1)
Internal Server Error: /myFollow/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 415, in my_follow
    userid = User.objects.filter(username = username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 923878|app: 0|req: 7/33] 60.181.111.149 () {50 vars in 918 bytes} [Fri Apr  8 06:44:45 2022] POST /myFollow/ => generated 58943 bytes in 174 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
Internal Server Error: /api/Groups/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 797, in groups
    user_id = User.objects.filter(username=username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 923878|app: 0|req: 7/34] 60.181.111.149 () {50 vars in 922 bytes} [Fri Apr  8 06:44:45 2022] POST /api/Groups/ => generated 59279 bytes in 173 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.20 (64bit) on [Fri Apr  8 14:46:32 2022] ***
compiled with version: 9.3.0 on 06 March 2022 03:37:57
os: Linux-5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
nodename: VM-20-8-ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/wwwroot/CSC4001_Project/Code
writing pidfile to uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /data/wwwroot/CSC4001_Project/Code/backend/
your processes number limit is 15359
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...567 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
Python main interpreter initialized at 0x55cfc3d32d40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55cfc3d32d40 pid: 928400 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 928400)
spawned uWSGI worker 1 (pid: 928423, cores: 2)
spawned uWSGI worker 2 (pid: 928424, cores: 2)
spawned uWSGI worker 3 (pid: 928425, cores: 2)
spawned uWSGI worker 4 (pid: 928426, cores: 2)
Internal Server Error: /mainpage/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 363, in main_page
    userid = User.objects.filter(username = username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 928426|app: 0|req: 1/1] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:46:39 2022] POST /mainpage/ => generated 58949 bytes in 548 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
Internal Server Error: /myFollow/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 415, in my_follow
    userid = User.objects.filter(username = username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 928424|app: 0|req: 1/2] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:46:39 2022] POST /myFollow/ => generated 58923 bytes in 605 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
Internal Server Error: /api/Groups/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 797, in groups
    user_id = User.objects.filter(username=username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 928425|app: 0|req: 1/3] 60.181.111.149 () {50 vars in 902 bytes} [Fri Apr  8 06:46:39 2022] POST /api/Groups/ => generated 59259 bytes in 634 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
Internal Server Error: /api/MyGroups/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 841, in MyGroups
    response = groups(request, own = 1)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 797, in groups
    user_id = User.objects.filter(username=username).values()[0]['id']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 928423|app: 0|req: 2/4] 60.181.111.149 () {50 vars in 906 bytes} [Fri Apr  8 06:46:39 2022] POST /api/MyGroups/ => generated 62782 bytes in 670 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 1)
Internal Server Error: /api/getProfile/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/wwwroot/CSC4001_Project/Code/backend/./Our_project/views.py", line 692, in getProfile
    photo_url = target_user[0]['photo']
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 322, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 928423|app: 0|req: 2/5] 60.181.111.149 () {50 vars in 910 bytes} [Fri Apr  8 06:46:39 2022] POST /api/getProfile/ => generated 59055 bytes in 685 msecs (HTTP/1.1 500) 9 headers in 327 bytes (1 switches on core 0)
[pid: 928424|app: 0|req: 3/6] 60.181.111.149 () {50 vars in 910 bytes} [Fri Apr  8 06:46:46 2022] POST /api/getProfile/ => generated 58 bytes in 57 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
[pid: 928424|app: 0|req: 3/7] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:46:46 2022] POST /myFollow/ => generated 2 bytes in 61 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 928423|app: 0|req: 4/8] 60.181.111.149 () {50 vars in 906 bytes} [Fri Apr  8 06:46:46 2022] POST /api/MyGroups/ => generated 2 bytes in 85 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
[pid: 928423|app: 0|req: 4/9] 60.181.111.149 () {50 vars in 902 bytes} [Fri Apr  8 06:46:46 2022] POST /api/Groups/ => generated 725 bytes in 95 msecs (HTTP/1.1 200) 9 headers in 305 bytes (1 switches on core 1)
[pid: 928426|app: 0|req: 2/10] 60.181.111.149 () {50 vars in 898 bytes} [Fri Apr  8 06:46:46 2022] POST /mainpage/ => generated 2503 bytes in 246 msecs (HTTP/1.1 200) 9 headers in 306 bytes (1 switches on core 1)
